FROM golang:${VERSION}-alpine
MAINTAINER Chris Garrett (https://github.com/chris-garrett/docker-golang)
LABEL description="Golang ${VERSION} Development Image"
RUN apk --no-cache add git \
                       bash \
                       make \
                       curl \
                       libintl \
                       gettext \
    && cp /usr/bin/envsubst /tmp/envsubst \
    && curl https://glide.sh/get | sh \
    && apk del gettext \
    && mv /tmp/envsubst /usr/bin/envsubst
