FROM golang:${GO_VERSION}-alpine
ARG VERSION
MAINTAINER Chris Garrett (https://github.com/chris-garrett/docker-golang)
LABEL description="Golang ${GO_VERSION} Development Image"
RUN apk --no-cache add git bash make curl
RUN curl https://glide.sh/get | sh
